export enum BuffType {
    INTERNAL = 0,
    AURA = 1,
    COMBAT_ENCHANCER = 2,
    COMBAT_DEHANCER = 3,
    SPELL_SHIELD = 4,
    STUN = 5,
    INVISIBILITY = 6,
    SILENCE = 7,
    TAUNT = 8,
    POLYMORPH = 9,
    SLOW = 10,
    SNARE = 11,
    DAMAGE = 12,
    HEAL = 13,
    HASTE = 14,
    SPELL_IMMUNITY = 15,
    PHYSICAL_IMMUNITY = 16,
    INVULNERABILITY = 17,
    SLEEP = 18,
    NEAR_SIGHT = 19,
    FRENZY = 20,
    FEAR = 21,
    NET = 22,
    POISON = 23,
    SUPPRESSION = 24,
    BLIND = 25,
    AMMO_STACK = 26,
    
    CHARM,
}

export enum BuffAddType
{
	UNDEFINED,
	REPLACE_EXISTING,
	RENEW_EXISTING,
	STACKS_AND_RENEWS,
	STACKS_AND_CONTINUE,
	STACKS_AND_OVERLAPS,
}

//TODO: Remove?
export enum EffCreate {
    UPDATE_ORIENTATION
}
